<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5BH.j.y' shared service.

return $this->privates['.service_locator.5BH.j.y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ad' => ['privates', '.errored..service_locator.5BH.j.y.App\\Entity\\Ad', NULL, 'Cannot autowire service ".service_locator.5BH.j.y": it references class "App\\Entity\\Ad" but no such service exists.'],
]);
