<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyNwdbb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyNwdbb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYyNwdbb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYyNwdbb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYyNwdbb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YyNwdbb',
    'container.build_id' => 'a3f7c5ea',
    'container.build_time' => 1556032261,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyNwdbb');
